---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "all"
  gather_facts: false
  tasks:

    - name: "Get Apache2 service current state"
      register: apache_service_status
      failed_when: not apache_service_status.status.ActiveState == 'active'
      ansible.builtin.systemd:
        name: "apache2"

    - name: "Check Apache2 folders and conf"
      loop:
        - "/etc/apache2/apache2.conf"
        - "/etc/apache2/ports.conf"
      loop_control:
        loop_var: folder_path
      register: folder_check
      failed_when: not folder_check.stat.exists
      ansible.builtin.stat:
        path: "{{ folder_path }}"

    - name: "Check Apache2 HTTP connectivity"
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ inv_apache_http_listen_port }}"
        timeout: 120

    - name: "Check Apache2 HTTPS connectivity"
      when: inv_apache_enable_default_vhosts
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ inv_apache_https_listen_port }}"
        timeout: 120

    - name: "Check Apache2 default configuration"
      block:
        - name: "Check default page on HTTP"
          register: result
          failed_when: result.status != 200
          ansible.builtin.uri:
            url: "http://{{ inventory_hostname }}:{{ inv_apache_http_listen_port }}/index.html"
            method: "GET"

        - name: "Check default page on HTTPS"
          when: inv_apache_enable_default_vhosts
          register: result
          failed_when: result.status != 200
          ansible.builtin.uri:
            url: "https://{{ inventory_hostname }}:{{ inv_apache_https_listen_port }}/index.html"
            method: "GET"
