---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_apache"
      tags:
        - "labocbz.install_apache"
      vars:
        apache_https_listen_port: "{{ inv_apache_https_listen_port }}"
        apache_http_listen_port: "{{ inv_apache_http_listen_port }}"
        apache_modules: "{{ inv_apache_modules }}"
        apache_enable_qos: "{{ inv_apache_enable_qos }}"
        apache_qos_client_entries: "{{ inv_apache_qos_client_entries }}"
        apache_qos_srv_max_conn_per_ip: "{{ inv_apache_qos_srv_max_conn_per_ip }}"
        apache_qos_max_clients: "{{ inv_apache_qos_max_clients }}"
        apache_qos_srv_max_conn_close: "{{ inv_apache_qos_srv_max_conn_close }}"
        apache_qos_srv_min_data_rate: "{{ inv_apache_qos_srv_min_data_rate }}"
        apache_enable_security: "{{ inv_apache_enable_security }}"
        apache_security_core_version: "{{ tower_apache_security_core_version }}"
        apache_enable_default_vhosts: "{{ tower_apache_enable_default_vhosts }}"
        apache_remove_all_no_default_vhosts: "{{ tower_apache_remove_all_no_default_vhosts }}"
      ansible.builtin.include_role:
        name: "labocbz.install_apache"
