---
- name: "Converge"
  hosts: "all:&local"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_apache"
      tags:
        - "labocbz.install_apache"
      vars:
        install_apache__https_listen_port: "{{ inv_install_apache__https_listen_port }}"
        install_apache__http_listen_port: "{{ inv_install_apache__http_listen_port }}"
        install_apache__modules: "{{ inv_install_apache__modules }}"
        install_apache__enable_qos: "{{ inv_install_apache__enable_qos }}"
        install_apache__enable_security: "{{ inv_install_apache__enable_security }}"
        install_apache__security_core_version: "{{ tower_install_apache__security_core_version }}"
        install_apache__remove_all_vhosts: "{{ tower_install_apache__remove_all_vhosts }}"
        install_apache__loglevel: "{{ inv_install_apache__loglevel }}"
        install_apache__security_version: "{{ tower_install_apache__security_version }}"
        install_apache__enable_evasive: "{{ inv_install_apache__enable_evasive }}"
        install_apache__enable_pagespeed: "{{ inv_install_apache__enable_pagespeed }}"
        install_apache__enable_prefork: "{{ inv_install_apache__enable_prefork }}"
      ansible.builtin.include_role:
        name: "labocbz.install_apache"
